url: https://simad.github.io
baseurl: 

# Site settings
title: Division by Zero
email: hello@divisionbyzero.co
description: "We make software for interesting humans. Work hard, experiments, solve problems, break the rules."

author:
  twitter: silmnd
gems:
  - jekyll-seo-tag
# Google services
google_analytics: UA-86013895-1

# Postal address (add as many lines as necessary)
address:
  - line: Division by Zero LTD
  - line: 2 Dolben Court
  - line: Montaigne Close
  - line: SW1P 4BB

# Build settings
markdown: kramdown
permalink: pretty